<?php
/**
 * GetWalletAssetDetailsRI
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  kocetestpack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultody
 *
 * Vaultody
 *
 * The version of the OpenAPI document: 2023-04-20
 * Contact: developers@vaultody.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kocetestpack\Model;

use \ArrayAccess;
use \kocetestpack\ObjectSerializer;

/**
 * GetWalletAssetDetailsRI Class Doc Comment
 *
 * @category Class
 * @package  kocetestpack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetWalletAssetDetailsRI implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetWalletAssetDetailsRI';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'confirmed_balance' => '\kocetestpack\Model\GetWalletAssetDetailsRIConfirmedBalance',
        'deposit_addresses_count' => 'int',
        'fungible_tokens' => '\kocetestpack\Model\GetWalletAssetDetailsRIFungibleTokensInner[]',
        'name' => 'string',
        'non_fungible_tokens' => '\kocetestpack\Model\GetWalletAssetDetailsRINonFungibleTokensInner[]',
        'recieved_confirmed_amount' => '\kocetestpack\Model\GetWalletAssetDetailsRIRecievedConfirmedAmount',
        'sent_confirmed_amount' => '\kocetestpack\Model\GetWalletAssetDetailsRISentConfirmedAmount'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'confirmed_balance' => null,
        'deposit_addresses_count' => null,
        'fungible_tokens' => null,
        'name' => null,
        'non_fungible_tokens' => null,
        'recieved_confirmed_amount' => null,
        'sent_confirmed_amount' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'confirmed_balance' => false,
		'deposit_addresses_count' => false,
		'fungible_tokens' => false,
		'name' => false,
		'non_fungible_tokens' => false,
		'recieved_confirmed_amount' => false,
		'sent_confirmed_amount' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'confirmed_balance' => 'confirmedBalance',
        'deposit_addresses_count' => 'depositAddressesCount',
        'fungible_tokens' => 'fungibleTokens',
        'name' => 'name',
        'non_fungible_tokens' => 'nonFungibleTokens',
        'recieved_confirmed_amount' => 'recievedConfirmedAmount',
        'sent_confirmed_amount' => 'sentConfirmedAmount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'confirmed_balance' => 'setConfirmedBalance',
        'deposit_addresses_count' => 'setDepositAddressesCount',
        'fungible_tokens' => 'setFungibleTokens',
        'name' => 'setName',
        'non_fungible_tokens' => 'setNonFungibleTokens',
        'recieved_confirmed_amount' => 'setRecievedConfirmedAmount',
        'sent_confirmed_amount' => 'setSentConfirmedAmount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'confirmed_balance' => 'getConfirmedBalance',
        'deposit_addresses_count' => 'getDepositAddressesCount',
        'fungible_tokens' => 'getFungibleTokens',
        'name' => 'getName',
        'non_fungible_tokens' => 'getNonFungibleTokens',
        'recieved_confirmed_amount' => 'getRecievedConfirmedAmount',
        'sent_confirmed_amount' => 'getSentConfirmedAmount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('confirmed_balance', $data ?? [], null);
        $this->setIfExists('deposit_addresses_count', $data ?? [], null);
        $this->setIfExists('fungible_tokens', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('non_fungible_tokens', $data ?? [], null);
        $this->setIfExists('recieved_confirmed_amount', $data ?? [], null);
        $this->setIfExists('sent_confirmed_amount', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['confirmed_balance'] === null) {
            $invalidProperties[] = "'confirmed_balance' can't be null";
        }
        if ($this->container['deposit_addresses_count'] === null) {
            $invalidProperties[] = "'deposit_addresses_count' can't be null";
        }
        if ($this->container['fungible_tokens'] === null) {
            $invalidProperties[] = "'fungible_tokens' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['non_fungible_tokens'] === null) {
            $invalidProperties[] = "'non_fungible_tokens' can't be null";
        }
        if ($this->container['recieved_confirmed_amount'] === null) {
            $invalidProperties[] = "'recieved_confirmed_amount' can't be null";
        }
        if ($this->container['sent_confirmed_amount'] === null) {
            $invalidProperties[] = "'sent_confirmed_amount' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets confirmed_balance
     *
     * @return \kocetestpack\Model\GetWalletAssetDetailsRIConfirmedBalance
     */
    public function getConfirmedBalance()
    {
        return $this->container['confirmed_balance'];
    }

    /**
     * Sets confirmed_balance
     *
     * @param \kocetestpack\Model\GetWalletAssetDetailsRIConfirmedBalance $confirmed_balance confirmed_balance
     *
     * @return self
     */
    public function setConfirmedBalance($confirmed_balance)
    {
        if (is_null($confirmed_balance)) {
            throw new \InvalidArgumentException('non-nullable confirmed_balance cannot be null');
        }
        $this->container['confirmed_balance'] = $confirmed_balance;

        return $this;
    }

    /**
     * Gets deposit_addresses_count
     *
     * @return int
     */
    public function getDepositAddressesCount()
    {
        return $this->container['deposit_addresses_count'];
    }

    /**
     * Sets deposit_addresses_count
     *
     * @param int $deposit_addresses_count Specifies the count of deposit addresses in the Wallet.
     *
     * @return self
     */
    public function setDepositAddressesCount($deposit_addresses_count)
    {
        if (is_null($deposit_addresses_count)) {
            throw new \InvalidArgumentException('non-nullable deposit_addresses_count cannot be null');
        }
        $this->container['deposit_addresses_count'] = $deposit_addresses_count;

        return $this;
    }

    /**
     * Gets fungible_tokens
     *
     * @return \kocetestpack\Model\GetWalletAssetDetailsRIFungibleTokensInner[]
     */
    public function getFungibleTokens()
    {
        return $this->container['fungible_tokens'];
    }

    /**
     * Sets fungible_tokens
     *
     * @param \kocetestpack\Model\GetWalletAssetDetailsRIFungibleTokensInner[] $fungible_tokens Represents fungible tokens'es detailed information
     *
     * @return self
     */
    public function setFungibleTokens($fungible_tokens)
    {
        if (is_null($fungible_tokens)) {
            throw new \InvalidArgumentException('non-nullable fungible_tokens cannot be null');
        }
        $this->container['fungible_tokens'] = $fungible_tokens;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Defines the name of the Wallet given to it by the user.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets non_fungible_tokens
     *
     * @return \kocetestpack\Model\GetWalletAssetDetailsRINonFungibleTokensInner[]
     */
    public function getNonFungibleTokens()
    {
        return $this->container['non_fungible_tokens'];
    }

    /**
     * Sets non_fungible_tokens
     *
     * @param \kocetestpack\Model\GetWalletAssetDetailsRINonFungibleTokensInner[] $non_fungible_tokens Represents non-fungible tokens'es detailed information.
     *
     * @return self
     */
    public function setNonFungibleTokens($non_fungible_tokens)
    {
        if (is_null($non_fungible_tokens)) {
            throw new \InvalidArgumentException('non-nullable non_fungible_tokens cannot be null');
        }
        $this->container['non_fungible_tokens'] = $non_fungible_tokens;

        return $this;
    }

    /**
     * Gets recieved_confirmed_amount
     *
     * @return \kocetestpack\Model\GetWalletAssetDetailsRIRecievedConfirmedAmount
     */
    public function getRecievedConfirmedAmount()
    {
        return $this->container['recieved_confirmed_amount'];
    }

    /**
     * Sets recieved_confirmed_amount
     *
     * @param \kocetestpack\Model\GetWalletAssetDetailsRIRecievedConfirmedAmount $recieved_confirmed_amount recieved_confirmed_amount
     *
     * @return self
     */
    public function setRecievedConfirmedAmount($recieved_confirmed_amount)
    {
        if (is_null($recieved_confirmed_amount)) {
            throw new \InvalidArgumentException('non-nullable recieved_confirmed_amount cannot be null');
        }
        $this->container['recieved_confirmed_amount'] = $recieved_confirmed_amount;

        return $this;
    }

    /**
     * Gets sent_confirmed_amount
     *
     * @return \kocetestpack\Model\GetWalletAssetDetailsRISentConfirmedAmount
     */
    public function getSentConfirmedAmount()
    {
        return $this->container['sent_confirmed_amount'];
    }

    /**
     * Sets sent_confirmed_amount
     *
     * @param \kocetestpack\Model\GetWalletAssetDetailsRISentConfirmedAmount $sent_confirmed_amount sent_confirmed_amount
     *
     * @return self
     */
    public function setSentConfirmedAmount($sent_confirmed_amount)
    {
        if (is_null($sent_confirmed_amount)) {
            throw new \InvalidArgumentException('non-nullable sent_confirmed_amount cannot be null');
        }
        $this->container['sent_confirmed_amount'] = $sent_confirmed_amount;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


