<?php
/**
 * CreateCoinsTransactionFromAddressForWholeAmountRBDataItemTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  kocetestpack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultody
 *
 * Vaultody
 *
 * The version of the OpenAPI document: 2023-04-20
 * Contact: developers@vaultody.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace kocetestpack\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateCoinsTransactionFromAddressForWholeAmountRBDataItemTest Class Doc Comment
 *
 * @category    Class
 * @description CreateCoinsTransactionFromAddressForWholeAmountRBDataItem
 * @package     kocetestpack
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateCoinsTransactionFromAddressForWholeAmountRBDataItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateCoinsTransactionFromAddressForWholeAmountRBDataItem"
     */
    public function testCreateCoinsTransactionFromAddressForWholeAmountRBDataItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fee_priority"
     */
    public function testPropertyFeePriority()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "recipient_address"
     */
    public function testPropertyRecipientAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
