<?php
/**
 * GetWalletTransactionDetailsByTransactionIDRIBSZVJoinSplitInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  kocetestpack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultody
 *
 * Vaultody
 *
 * The version of the OpenAPI document: 2023-04-20
 * Contact: developers@vaultody.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace kocetestpack\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetWalletTransactionDetailsByTransactionIDRIBSZVJoinSplitInnerTest Class Doc Comment
 *
 * @category    Class
 * @description GetWalletTransactionDetailsByTransactionIDRIBSZVJoinSplitInner
 * @package     kocetestpack
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetWalletTransactionDetailsByTransactionIDRIBSZVJoinSplitInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetWalletTransactionDetailsByTransactionIDRIBSZVJoinSplitInner"
     */
    public function testGetWalletTransactionDetailsByTransactionIDRIBSZVJoinSplitInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "anchor"
     */
    public function testPropertyAnchor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cipher_texts"
     */
    public function testPropertyCipherTexts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "commitments"
     */
    public function testPropertyCommitments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "macs"
     */
    public function testPropertyMacs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nullifiers"
     */
    public function testPropertyNullifiers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "one_time_pub_key"
     */
    public function testPropertyOneTimePubKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "proof"
     */
    public function testPropertyProof()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "random_seed"
     */
    public function testPropertyRandomSeed()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "v_pub_new"
     */
    public function testPropertyVPubNew()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "v_pub_old"
     */
    public function testPropertyVPubOld()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
