<?php
/**
 * GeneratingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  kocetestpack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultody
 *
 * Vaultody
 *
 * The version of the OpenAPI document: 2023-04-20
 * Contact: developers@vaultody.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace kocetestpack\Test\Api;

use \kocetestpack\Configuration;
use \kocetestpack\ApiException;
use \kocetestpack\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GeneratingApiTest Class Doc Comment
 *
 * @category Class
 * @package  kocetestpack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GeneratingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createNewMasterWallet
     *
     * Create New Master Wallet.
     *
     */
    public function testCreateNewMasterWallet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateDepositAddress
     *
     * Generate Deposit Address.
     *
     */
    public function testGenerateDepositAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
