<?php
/**
 * InformativeApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  kocetestpack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultody
 *
 * Vaultody
 *
 * The version of the OpenAPI document: 2023-04-20
 * Contact: developers@vaultody.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace kocetestpack\Test\Api;

use \kocetestpack\Configuration;
use \kocetestpack\ApiException;
use \kocetestpack\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InformativeApiTest Class Doc Comment
 *
 * @category Class
 * @package  kocetestpack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InformativeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getTransactionRequestDetails
     *
     * Get Transaction Request Details.
     *
     */
    public function testGetTransactionRequestDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWalletAssetDetails
     *
     * Get Wallet Asset Details.
     *
     */
    public function testGetWalletAssetDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWalletTransactionDetailsByTransactionID
     *
     * Get Wallet Transaction Details By Transaction ID.
     *
     */
    public function testGetWalletTransactionDetailsByTransactionID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAllAssetsByWalletID
     *
     * List All Assets By Wallet ID.
     *
     */
    public function testListAllAssetsByWalletID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAllAssetsFromAllWallets
     *
     * List All Assets From All Wallets.
     *
     */
    public function testListAllAssetsFromAllWallets()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDepositAddresses
     *
     * List Deposit Addresses.
     *
     */
    public function testListDepositAddresses()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSupportedTokens
     *
     * List Supported Tokens.
     *
     */
    public function testListSupportedTokens()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWalletTransactions
     *
     * List Wallet Transactions.
     *
     */
    public function testListWalletTransactions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
