<?php
/**
 * TransactionsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  kocetestpack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultody
 *
 * Vaultody
 *
 * The version of the OpenAPI document: 2023-04-20
 * Contact: developers@vaultody.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace kocetestpack\Test\Api;

use \kocetestpack\Configuration;
use \kocetestpack\ApiException;
use \kocetestpack\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransactionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  kocetestpack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createCoinsTransactionFromAddressForWholeAmount
     *
     * Create Coins Transaction From Address For Whole Amount.
     *
     */
    public function testCreateCoinsTransactionFromAddressForWholeAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCoinsTransactionRequestFromAddress
     *
     * Create Coins Transaction Request from Address.
     *
     */
    public function testCreateCoinsTransactionRequestFromAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCoinsTransactionRequestFromWallet
     *
     * Create Coins Transaction Request from Wallet.
     *
     */
    public function testCreateCoinsTransactionRequestFromWallet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createFungibleTokenTransactionRequestFromAddressWithoutFeePriority
     *
     * Create Fungible Token Transaction Request From Address Without Fee Priority.
     *
     */
    public function testCreateFungibleTokenTransactionRequestFromAddressWithoutFeePriority()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createFungibleTokensTransactionRequestFromAddress
     *
     * Create Fungible Tokens Transaction Request From Address.
     *
     */
    public function testCreateFungibleTokensTransactionRequestFromAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSingleTransactionRequestFromAddressWithoutFeePriority
     *
     * Create Single Transaction Request From Address Without Fee Priority.
     *
     */
    public function testCreateSingleTransactionRequestFromAddressWithoutFeePriority()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
